-- Notification type seed. Stable codes TN001-TN030.

INSERT IGNORE INTO `tipe_notifikasi` (`id_tipe_notifikasi`, `deskripsi`, `konteks`) VALUES
('TN001', 'Permohonan FPPL diterima dan diverifikasi', 'FPPL'),
('TN002', 'Permohonan FPPL ditolak', 'FPPL'),
('TN003', 'Permohonan FPPL diproses', 'FPPL'),
('TN004', 'Tagihan siap, menunggu pembayaran', 'FPPL'),
('TN005', 'Pembayaran telah diverifikasi', 'FPPL'),
('TN006', 'Sampel belum diterima laboratorium', 'FPPL'),
('TN007', 'Jadwal pengambilan LHU telah ditentukan', 'JADWAL_LHU'),
('TN008', 'LHU sudah selesai dan siap diambil', 'LHU'),
('TN009', 'Permohonan baru masuk ke admin', 'FPPL'),
('TN010', 'Analis mendapat penugasan baru', 'PENUGASAN'),
('TN011', 'Detail penugasan analis diperbarui', 'PENUGASAN'),
('TN012', 'Hasil pengujian diminta revisi oleh Penyelia', 'PENUGASAN'),
('TN013', 'Hasil pengujian diminta revisi oleh Kasi Pengujian', 'PENUGASAN'),
('TN014', 'Penyelia perlu mengisi hasil pengujian subkontrak', 'PENUGASAN'),
('TN015', 'Deadline pengujian analis sudah dekat', 'PENUGASAN'),
('TN016', 'Analis selesai mengisi hasil dan submit ke Penyelia', 'PENUGASAN'),
('TN017', 'Jadwal pengantaran/pengambilan sampel telah ditentukan', 'FPPL'),
('TN018', 'Kasi Pengujian perlu menentukan metode pengujian', 'FPPL'),
('TN019', 'Penyelia perlu menugaskan pengujian sampel masuk', 'PENUGASAN'),
('TN020', 'LHU menunggu persetujuan Kepala Lab', 'LHU'),
('TN021', 'Pelanggan mengajukan perubahan jadwal', 'JADWAL'),
('TN022', 'Pengajuan perubahan jadwal disetujui admin', 'JADWAL'),
('TN023', 'Pengajuan perubahan jadwal ditolak admin', 'JADWAL'),
('TN024', 'Penyelia menyetujui LKA dan mengirim hasil ke Kasi Pengujian', 'PENUGASAN'),
('TN025', 'Semua LHU pada satu permohonan sudah disahkan dan perlu dijadwalkan admin', 'LHU'),
('TN026', 'Revisi Kasi Pengujian menunggu persetujuan Penyelia', 'PENUGASAN'),
('TN027', 'Revisi Kasi Pengujian ditolak oleh Penyelia', 'PENUGASAN'),
('TN028', 'Revisi hasil dari Analis siap direview ulang Kasi Pengujian', 'PENUGASAN'),
('TN029', 'Deadline pengujian analis terlewat', 'PENUGASAN'),
('TN030', 'Bukti pembayaran pelanggan menunggu verifikasi admin', 'FPPL');
